<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="QT-UK-LT1395" failures="1" tests="1" name="PositiveTest" time="9.946" errors="0" timestamp="2022-03-21T17:07:40 GMT">
  <testcase classname="com.herokuapp.theinternet.PositiveTest" name="loginTest" time="9.905">
    <failure type="java.lang.AssertionError" message="Actual message is not the same as expected expected [You logged out of the secure area!
×] but found [You logged out of the secure area!
Ã—]">
      <![CDATA[java.lang.AssertionError: Actual message is not the same as expected expected [You logged out of the secure area!
×] but found [You logged out of the secure area!
Ã—]
at com.herokuapp.theinternet.PositiveTest.loginTest(PositiveTest.java:66)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
</testsuite> <!-- PositiveTest -->
